name: msbuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
 
    runs-on: windows-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
            
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore pac-wrapper-dll.sln

      - name: Build and Publish Web App
        run: msbuild pac-wrapper-dll.sln /p:Configuration=Release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2